spring:
  datasource:
    url: jdbc:h2:mem:rulesdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none  # Let schema.sql handle it
    show-sql: true
  sql:
    init:
      mode: always
